Server.port=8080
spring.application.name=phone-tracker
spring.data.mongodb.uri=mongodb://localhost:27017/phone-tracker
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=phone-tracker_db
